### PR TITLE
Feat: Added Card and Footer Component

### PR DESCRIPTION
**Pull request by SaurabhChawda**
Added two components Card Component and Footer Component.
Screenshot (320)

### CODE REVIEW

**Review by mariyasada — APPROVED** [review]
good to merge but your deploy preview is not working

**Review by JantuDeb — APPROVED** [review]
Overall the codes looking good

**Comment by SaurabhChawda** [comment]
> good to merge but your deploy preview is not working.
Yes, I don't know why it is not working , ThankYou

**Comment by SaurabhChawda** [comment]
> Overall the codes looking good

ThankYou

**Pull request merged**
